### ISSUE TITLE
apps_dns haproxy configuration not done on bastion server ?

### ISSUE THREAD

**Issue by radtriste** [RedHat-EMEA-SSA-Team/stc#65]
Hello,

extract from env.yml:

```yaml
ocp_version: 3.11
api_dns: redhat-cluster.muc.lv1871.de
apps_dns: redhat.muc.lv1871.de
bastion: redhat-bastion.muc.lv1871.de
lb: redhat-bastion.muc.lv1871.de
```

I managed to install my cluster. I can reach the api_dns: https://redhat-cluster.muc.lv1871.de:8443/console.
But I have problems with *.redhat.muc.lv1871.de urls.

For example, I try to go to console.redhat.muc.lv1871.de or metrics.redhat.muc.lv1871.de but I cannot reach it.
I tried a small ping on it and it reaches my bastion server without any problem.

It seems so that my haproxy configuration is not done ...
Here is the current content:

```
# Global settings
#---------------------------------------------------------------------
global
    maxconn     20000
    log         /dev/log local0 info
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    user        haproxy
    group       haproxy
    daemon

    # turn on stats unix socket
    stats socket /var/lib/haproxy/stats

#---------------------------------------------------------------------
# common defaults that all the 'listen' and 'backend' sections will
# use if not designated in their block
#---------------------------------------------------------------------
defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
#    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          300s
    timeout server          300s
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 20000

listen stats
    bind :9000
    mode http
    stats enable
    stats uri /

frontend  atomic-openshift-api
    bind *:8443
    default_backend atomic-openshift-api
    mode tcp
    option tcplog

backend atomic-openshift-api
    balance source
    mode tcp
    server      master0 10.6.22.59:8443 check
    server      master1 10.6.22.60:8443 check
    server      master2 10.6.22.61:8443 check
```

I am no expert in haproxy but it seems to me that there is no configuration for ports 80/443 ...

What should be the configuration ?
Is it part of the scripts ?

**Comment by tahonen** [comment]
It seems that router routing rules are not added there during install...only master ones.

you can fix issue by adding these configs
frontend  apps-http
    bind *:80
    default_backend apps-http
    mode tcp
    option tcplog

backend apps-http
    balance source
    mode tcp
    server      infra0 INFRA_NODE_IP:80 check
    server      infra1 INFRA_NODE_IP:80 check
    server      infra3 INFRA_NODE_IP:80 check

frontend  apps-https
    bind *:443
    default_backend apps-https
    mode tcp
    option tcplog

backend apps-https
    balance source
    mode tcp
    server      infra0 INFRA_NODE_IP:443 check
    server      infra1 INFRA_NODE_IP:443 check
    server      infra3 INFRA_NODE_IP:443 check

If you have one or two infra nodes remove extra ones. Then restart haproxy on bastion

**Comment by radtriste** [comment]
Works like a charm. Thank you !
