### ISSUE TITLE
Add storageclass name for prometheus operator

### ISSUE THREAD

**Issue by blues-man** [RedHat-EMEA-SSA-Team/stc#67]
https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_cluster_monitoring_operator/defaults/main.yml#L48

**Comment by rbo** [comment]
New Link: https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_cluster_monitoring_operator/defaults/main.yml#L48
