### ISSUE TITLE
non interactive setup

### ISSUE THREAD

**Issue by DanielFroehlich** [RedHat-EMEA-SSA-Team/stc#86]
As an STC user, I would like to be able to run a STC setup from a toplevel ansible playbook, requiring non-interactive mode without manual user input.

Currently,  setup.sh is always requiring manual input which prohibits me running it fully automated.

**Comment by rbo** [comment]
Indeed, setup.sh is for human interaction. 

The **Current behavior** is:

`./setup.sh` does:
1) Creates env.yml
2) Checks (enabled repos) and prepare bastion (install packages)
3) Create an inventory file 
   - `ansible-playbook playbooks/validate_config.yml` - ask for sudo pw and create (secret.yml)
4) Encrypt secrets.yml
   - `ansible-vault encrypt secrets.yml`
5) Prepare ssh 
    - `ansible-playbook -i inventory -k --ask-vault-pass playbooks/prepare_ssh.yml`
6) copy `inventory` to `/etc/ansible/hosts`

and then: `ansible-playbook --ask-vault playbooks/validate.yml`

For better automation I can image following new behavior:

**Interactive setup**
Run Setup.sh and it does:
1) Creates env.yml
2) Checks (enabled repos) and prepare bastion (install packages)
3) Ask for sudo ps and create encrypted secrets.yml
4) Create an inventory file - **without any interaction!**
   - `ansible-playbook playbooks/validate_config.yml`
5) Prepare ssh 
    - `ansible-playbook -i inventory -k --ask-vault-pass playbooks/prepare_ssh.yml`

and then: `ansible-playbook --ask-vault playbooks/validate.yml`

**non interactive setup**
Takes care of steps 1,2,3 and 5 from Interactive setup and then can simply run:
```
ansible-playbook playbooks/validate_config.yml
ansible-playbook --ask-vault playbooks/validate.yml
```

What do you think @DanielFroehlich ?

**Comment by rbo** [comment]
Please check out @DanielFroehlich full automated provisioning with STC: https://github.com/RedHat-EMEA-SSA-Team/stc/blob/master/hack/kcli-plan/files/install-ocp.sh

**Comment by rbo** [comment]
From my point of view, we can close the Issue. Because of OCP 4 it makes no sense to do fundamental changes.

**Comment by DanielFroehlich** [comment]
I tried this approach to deploy ocp3 on stormshift, and it works nicely.
Just wondering: running the validate playbook is very quick, while running the "setup.sh" takes ages. But it trust that this is due to skipping all repo enabled and preparation stuff, which my playbooks do already also. As the install of ocp3 worked like a charm, I happy and close this issue for now. Thx!
